### ISSUE TITLE
Release of latest code version?

### ISSUE THREAD

**Issue by b-a0** [zybexXL/EFUtool#2]
Hi, I really appreciate this tool as it improves the speed of updating Everything filelists.
Is it possible to release the latest code (with [the last commit in September 2020](https://github.com/zybexXL/EFUtool/commits/master)) in the releases? I am not familiar with C# and not sure how to build it myself.

Thanks in advance!

**Comment by zybexXL** [comment]
Hi @b-a0, thanks for the heads up! It looks like I forgot to publish the binary for those changes. I just did it now:
https://github.com/zybexXL/EFUtool/releases

Also note the -a and -p options are changed. Perhaps you should create new EFUs once (instead of just updating) with this version.

**Comment by b-a0** [comment]
Thanks for the fast reponse!
